# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
container: "docker://continuumio/miniconda3"



from snakemake.utils import validate
import pandas as pd
import random

# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"

##### load config and sample sheets #####

configfile: "../config/config.yaml"
validate(config, schema="schemas/config.schema.yaml")

samples = pd.read_csv(config["samples"], sep="\t").set_index("sample", drop=False)
samples.index.names = ["sample_id"]
validate(samples, schema="schemas/samples.schema.yaml")


##### set seed #####

random.seed(config["seed"])
samples["seed"] = [random.randint(0,99999999) for i in range(0,len(samples))]

##### rules ####

rule all:
    input:
        expand("results/workflow/{assembly}/{sample}.fa.gz", sample=samples.index, assembly="GRCh38")
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.

include: "rules/common.smk"
