$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:

  samples:
    type: string

  assembly:
    type: object
    additionalProperties:
      type: object
      properties:
        release:
          type: string
        fasta:
          type: string
        genome:
          type: string
      required:
        - release
        - fasta
        - genome
  
  intervals:
    type: object
    properties:
      length:
        type: integer
    required:
      - length

  seed:
    type: integer

# entries that have to be in the config file for successful validation
required:
  - samples
  - assembly
  - intervals
  - seed
